
## What?


Naylang is the new interpreter, runtime and debugger for a subset of the [Grace Programming Language](http://gracelang.org/applications/).
It's still a work in progress, but it has some great features already!

## How?

To use Naylang, just download the executable for the [latest release](https://github.com/blorente/naylang/releases) and start it up in a terminal!

If you'd rather compile it from source [click me!](#compilation-instructions)


